# Generated by Django 4.1.4 on 2023-01-03 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('total_points', models.IntegerField()),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizz.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('multiple_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentStatics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('status', models.BooleanField()),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizz.lesson')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuestionStatics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_status', models.BooleanField()),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizz.question')),
                ('statics', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizz.studentstatics')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizz.questiontype'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('correct', models.BooleanField()),
                ('points', models.IntegerField()),
                ('question_content', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizz.question')),
            ],
        ),
    ]
